version: '3.9'

services:
  mongodb:
    image: 'mongo:7'
    container_name: mongoDB
    ports:
      - '27017:27017'
    environment:
      - 'USERNAME=admin'
      - 'PASSWORD=secret'
    volumes:
      - mongo-data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - mongonet

volumes:
    mongo-data:

networks:
  mongonet:
    driver: bridge

